oaconfig: fixed indentation with tabs
Signed-off-by: Ricardo Dias <rdias@suse.com>

diff --git a/bin/oaconfig b/bin/oaconfig
--- a/bin/oaconfig
+++ b/bin/oaconfig
@@ -109,14 +109,14 @@ case $1 in
 
 		db_name=$(sed -rn 's/[ \t]*name[ \t]*=[ \t]*(.*)[ \t]*/\1/p' $database_ini)
 		if [[ -z $db_name ]]; then
-		  echo "ERROR: No database name defined in $database_ini"
-		  exit 1
+			echo "ERROR: No database name defined in $database_ini"
+			exit 1
 		fi
 
 		db_user=$(sed -rn 's/[ \t]*user[ \t]*=[ \t]*(.*)[ \t]*/\1/p' $database_ini)
 		if [[ -z $db_user ]]; then
-		  echo "ERROR: No database username defined in $database_ini"
-		  exit 1
+			echo "ERROR: No database username defined in $database_ini"
+			exit 1
 		fi
 
 		if (( has_local_database )) ; then
