Make `oaconfig install` create db credentials if necessary (OP-1757)
Signed-off-by: Patrick Nawracay <patrick@openattic.org>

diff --git a/bin/oaconfig b/bin/oaconfig
--- a/bin/oaconfig
+++ b/bin/oaconfig
@@ -99,29 +99,49 @@ case $1 in
 			service postgresql start
 		fi
 
+		pgsql_ini="/etc/openattic/databases/pgsql.ini"
+		# Check if the database role 'openattic' exists and creates it if it doesn't exist.
+		if ! sudo -u postgres psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='openattic'" | grep -q 1 ; then
+			echo "Creating database role \"openattic\""
+			pass=$(openssl rand -hex 10)
+			sed -ri "s/(password[ \t]*=[ \t]*)(.*)/\1${pass}/g" $pgsql_ini
+			if [ $? -ne 0 ]; then
+				echo "Failed to update $pgsql_ini"
+				exit 2
+			fi
+
+			su - postgres -c "psql -c \"CREATE USER openattic WITH PASSWORD '$pass'\""
+			echo "User 'openattic' created"
+		fi
+
+		# Check if database 'openattic' exists and creates it if it doesn't.
 		dbu=$(su - postgres -c "psql --list" | awk -F'|' ' /openattic/ { print $2 }')
 		if [ -n "$dbu" ]; then
 			echo "Database openattic exists, owned by $dbu"
 		else
-			# Initialize database
-			pass=$(openssl rand -hex 10)
-			PGSQL_INI="/etc/openattic/databases/pgsql.ini"
-			sed -i 's/DB_PASSWORD/'$pass'/' $PGSQL_INI
-			if [ $? -ne 0 ]; then
-				echo "Failed to update $PGSQL_INI"
-				exit 2
-			fi
-			su - postgres -c psql << EOT
-create user openattic with password '$pass';
-create database openattic with owner openattic;
-\q
-EOT
+			su - postgres -c "psql -c \"CREATE DATABASE openattic WITH OWNER openattic\""
+
 			hba_conf="/var/lib/pgsql/data/pg_hba.conf"
 			if [ -e ${hba_conf} ] ; then
 				sed -i -e 's/ident$/md5/g' ${hba_conf}
 			fi
 			service postgresql reload
 			service postgresql status
+		fi
+
+		# Check if the connection can be established with the database user and password.
+		# Set a new password if the connetion cannot be established.
+		password=$(sed -rn 's/^[ \t]*password[ \t]*=[ \t]*(.*)[ \t]*/\1/p' $pgsql_ini)
+		if ! PGPASSWORD=$password psql openattic openattic -h localhost --no-password -c "\q" ; then
+			pass=$(openssl rand -hex 10)
+			sed -ri "s/(password[ \t]*=[ \t]*)(.*)/\1${pass}/g" $pgsql_ini
+			if [ $? -ne 0 ]; then
+				echo "Failed to update $pgsql_ini"
+				exit 2
+			fi
+
+			su - postgres -c "psql -c \"ALTER USER openattic WITH PASSWORD '$pass'\""
+			echo "Password of database user openattic and database.ini updated"
 		fi
 		
 		su "$OAUSER" -c 'python manage.py pre_install'
