Create a random password for new pgsql instances
Signed-off-by: Patrick Nawracay <patrick@openattic.org>

diff --git a/bin/oaconfig b/bin/oaconfig
--- a/bin/oaconfig
+++ b/bin/oaconfig
@@ -93,6 +93,44 @@ case $1 in
 				exit 2
 			fi
 		fi
+
+		if ! service postgresql status >/dev/null; then
+			# Start database
+			service postgresql enable # ???
+			service postgresql start
+
+			# RedHat family only
+			POSTGRESQL_SETUP=`which postgresql-setup 2>/dev/null`
+			if [ -n "$POSTGRESQL_SETUP" ]; then
+				if $POSTGRESQL_SETUP initdb; then
+					echo "postgresql database initialized";
+				else
+					echo "postgres database already initialized";
+				fi
+			fi
+		fi
+
+		dbu=$(su - postgres -c "psql --list" | awk -F'|' ' /openattic/ { print $2 }')
+		if [ -n "$dbu" ]; then
+			echo "Database openattic exists, owned by $dbu"
+		else
+			# Initialize database
+			pass=$(openssl rand -hex 10)
+			PGSQL_INI="/etc/openattic/databases/pgsql.ini"
+			sed -i 's/DB_PASSWORD/'$pass'/' $PGSQL_INI
+			if [ $? -ne 0 ]; then
+				echo "Failed to update $PGSQL_INI"
+				exit 2
+			fi
+			su - postgres -c psql << EOT
+create user openattic with password '$pass';
+create database openattic with owner openattic;
+\q
+EOT
+			sed -i -e 's/ident$/md5/g' /var/lib/pgsql/data/pg_hba.conf
+			service postgresql reload
+			service postgresql status
+		fi
 		
 		su "$OAUSER" -c 'python manage.py pre_install'
 		
