automatically configure pam-pgsql and libnss-pgsql

diff --git a/debian/openattic-pgsql.postinst b/debian/openattic-pgsql.postinst
--- a/debian/openattic-pgsql.postinst
+++ b/debian/openattic-pgsql.postinst
@@ -2,20 +2,33 @@
 
 set -e
 
-. /usr/share/debconf/confmodule
+if [ "$1" = "configure" ] ; then
+    . /usr/share/debconf/confmodule
 
-. /usr/share/dbconfig-common/dpkg/postinst.pgsql
+    . /usr/share/dbconfig-common/dpkg/postinst.pgsql
 
-INIFILE=/etc/openattic/databases/pgsql.ini
+    INIFILE=/etc/openattic/databases/pgsql.ini
 
-dbc_generate_include_args="-o template_infile=/etc/openattic/databases/pgsql_template.ini"
-dbc_generate_include="template:$INIFILE"
+    dbc_generate_include_args="-o template_infile=/etc/openattic/databases/pgsql_template.ini"
+    dbc_generate_include="template:$INIFILE"
 
-if ! dbc_go openattic-pgsql $@ ; then
-    echo 'Automatic configuration using dbconfig-common failed!'
-else
-    dpkg-statoverride --list "$INIFILE" >/dev/null || \
-        dpkg-statoverride --update --add www-data www-data "0600" "$INIFILE"
+    if ! dbc_go openattic-pgsql $@ ; then
+        echo 'Automatic configuration using dbconfig-common failed!'
+    else
+        dpkg-statoverride --list "$INIFILE" >/dev/null || \
+            dpkg-statoverride --update --add www-data www-data "0600" "$INIFILE"
+    fi
+
+    dbconfig-generate-include -f template \
+        -o template_infile=/etc/openattic/databases/pam_pgsql_template.conf \
+        /etc/dbconfig-common/openattic-pgsql.conf \
+        /etc/pam_pgsql.conf
+
+    dbconfig-generate-include -f template \
+        -o template_infile=/etc/openattic/databases/nss_pgsql_template.conf \
+        /etc/dbconfig-common/openattic-pgsql.conf \
+        /etc/nss-pgsql.conf
 fi
+
 
 #DEBHELPER#
